image: docker:stable

services:
  - docker:dind

before_script:
  - docker login -p ${DOCKER_LOGIN_USER} -u ${DOCKER_LOGIN_PASSWORD}

build:
  stage: build
  script:
    - docker build -t ${REPOSITORY_NAME}:${CI_COMMIT_TAG:-devel} .
    - docker push ${REPOSITORY_NAME}:${CI_COMMIT_TAG:-devel}

build_arm:
  stage: build
  script:
    - docker build -t ${REPOSITORY_NAME}/arm:${CI_COMMIT_TAG:-devel} .
    - docker push ${REPOSITORY_NAME}/arm:${CI_COMMIT_TAG:-devel}
  tags:
    - arm